// <auto-generated />
using System;
using Data.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Core.Migrations
{
    [DbContext(typeof(BeeDbContext))]
    [Migration("20240929095659_mig10082024_21")]
    partial class mig10082024_21
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Data.Core.Models.BeeQueen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("BeeQueen", (string)null);
                });

            modelBuilder.Entity("Data.Core.Models.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("Data.Core.Models.DescriptionHiveReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.HasIndex("HiveId");

                    b.HasIndex("ReviewId");

                    b.ToTable("DescriptionHiveReview", (string)null);
                });

            modelBuilder.Entity("Data.Core.Models.Hive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddBeeQueenDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BeeQueenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNucleus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeeQueenId")
                        .IsUnique();

                    b.ToTable("Hive", (string)null);
                });

            modelBuilder.Entity("Data.Core.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalNotificationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NotifyTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Data.Core.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Data.Core.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductionTypeId");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("Data.Core.Models.ProductionHive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HiveId");

                    b.HasIndex("ProductionId");

                    b.ToTable("ProductionHives");
                });

            modelBuilder.Entity("Data.Core.Models.ProductionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductionTypeId");

                    b.ToTable("ProductionTypes");
                });

            modelBuilder.Entity("Data.Core.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Higienicznosc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lagodnosc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Licznosc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Produktywnosc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rojliwosc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Data.Core.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RealizedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewTypeId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Data.Core.Models.ReviewType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReviewTypes");
                });

            modelBuilder.Entity("Data.Core.Models.StockAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StockAvailabilities");
                });

            modelBuilder.Entity("Data.Core.Models.BeeQueen", b =>
                {
                    b.HasOne("Data.Core.Models.Race", "Race")
                        .WithMany("BeeQueens")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Data.Core.Models.DescriptionHiveReview", b =>
                {
                    b.HasOne("Data.Core.Models.Description", "Description")
                        .WithOne("DescriptionHiveReview")
                        .HasForeignKey("Data.Core.Models.DescriptionHiveReview", "DescriptionId");

                    b.HasOne("Data.Core.Models.Hive", "Hive")
                        .WithMany("DescriptionHiveReviews")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Core.Models.Review", "Review")
                        .WithMany("DescriptionHiveReviews")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("Hive");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Data.Core.Models.Hive", b =>
                {
                    b.HasOne("Data.Core.Models.BeeQueen", "BeeQueen")
                        .WithOne("Hive")
                        .HasForeignKey("Data.Core.Models.Hive", "BeeQueenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BeeQueen");
                });

            modelBuilder.Entity("Data.Core.Models.Notification", b =>
                {
                    b.HasOne("Data.Core.Models.Review", "Review")
                        .WithMany("Notifications")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Data.Core.Models.Photo", b =>
                {
                    b.HasOne("Data.Core.Models.Description", "Description")
                        .WithMany("Photos")
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("Data.Core.Models.Production", b =>
                {
                    b.HasOne("Data.Core.Models.ProductionType", "ProductionType")
                        .WithMany()
                        .HasForeignKey("ProductionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionType");
                });

            modelBuilder.Entity("Data.Core.Models.ProductionHive", b =>
                {
                    b.HasOne("Data.Core.Models.Hive", "Hive")
                        .WithMany("ProductionHives")
                        .HasForeignKey("HiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Core.Models.Production", "Production")
                        .WithMany("ProductionHives")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hive");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("Data.Core.Models.ProductionType", b =>
                {
                    b.HasOne("Data.Core.Models.ProductionType", null)
                        .WithMany("ProductionTypes")
                        .HasForeignKey("ProductionTypeId");
                });

            modelBuilder.Entity("Data.Core.Models.Review", b =>
                {
                    b.HasOne("Data.Core.Models.ReviewType", "ReviewType")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewType");
                });

            modelBuilder.Entity("Data.Core.Models.BeeQueen", b =>
                {
                    b.Navigation("Hive")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Core.Models.Description", b =>
                {
                    b.Navigation("DescriptionHiveReview")
                        .IsRequired();

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Data.Core.Models.Hive", b =>
                {
                    b.Navigation("DescriptionHiveReviews");

                    b.Navigation("ProductionHives");
                });

            modelBuilder.Entity("Data.Core.Models.Production", b =>
                {
                    b.Navigation("ProductionHives");
                });

            modelBuilder.Entity("Data.Core.Models.ProductionType", b =>
                {
                    b.Navigation("ProductionTypes");
                });

            modelBuilder.Entity("Data.Core.Models.Race", b =>
                {
                    b.Navigation("BeeQueens");
                });

            modelBuilder.Entity("Data.Core.Models.Review", b =>
                {
                    b.Navigation("DescriptionHiveReviews");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Data.Core.Models.ReviewType", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
