//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApp.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Add {
            get {
                return ResourceManager.GetString("txt_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_AddHive {
            get {
                return ResourceManager.GetString("txt_AddHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nową królową .
        /// </summary>
        internal static string txt_AddNewQueen {
            get {
                return ResourceManager.GetString("txt_AddNewQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Queen.
        /// </summary>
        internal static string txt_AddQueen {
            get {
                return ResourceManager.GetString("txt_AddQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_AddStock {
            get {
                return ResourceManager.GetString("txt_AddStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie.
        /// </summary>
        internal static string txt_All {
            get {
                return ResourceManager.GetString("txt_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryDataNavigationTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryDataNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryDataProdutionsMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryDataProdutionsMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryDataRacesMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryDataRacesMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryDataReviewsMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryDataReviewsMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryNavigationTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryProductionCreatorMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryProductionCreatorMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryProductionNavigationTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryProductionNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryProductionSummaryMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryProductionSummaryMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryToolsNavigationTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryToolsNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ApiaryToolSyrupCalculatorMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ApiaryToolSyrupCalculatorMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt_AppName.
        /// </summary>
        internal static string txt_AppName {
            get {
                return ResourceManager.GetString("txt_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string txt_BirthDate {
            get {
                return ResourceManager.GetString("txt_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Calculate {
            get {
                return ResourceManager.GetString("txt_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_CalculationTargetType {
            get {
                return ResourceManager.GetString("txt_CalculationTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string txt_Cancel {
            get {
                return ResourceManager.GetString("txt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ChooseLanguage {
            get {
                return ResourceManager.GetString("txt_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Clear {
            get {
                return ResourceManager.GetString("txt_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ClearDataBase {
            get {
                return ResourceManager.GetString("txt_ClearDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ClearDataBaseConfirmationText {
            get {
                return ResourceManager.GetString("txt_ClearDataBaseConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt_CountableUnit.
        /// </summary>
        internal static string txt_CountableUnit {
            get {
                return ResourceManager.GetString("txt_CountableUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Review.
        /// </summary>
        internal static string txt_CreateReview {
            get {
                return ResourceManager.GetString("txt_CreateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_DataSettingsMainPageTitle {
            get {
                return ResourceManager.GetString("txt_DataSettingsMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Date {
            get {
                return ResourceManager.GetString("txt_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Dead {
            get {
                return ResourceManager.GetString("txt_Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string txt_Delete {
            get {
                return ResourceManager.GetString("txt_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string txt_Description {
            get {
                return ResourceManager.GetString("txt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("txt_DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Review.
        /// </summary>
        internal static string txt_DetailsReview {
            get {
                return ResourceManager.GetString("txt_DetailsReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_DoubleValue {
            get {
                return ResourceManager.GetString("txt_DoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ForSugar {
            get {
                return ResourceManager.GetString("txt_ForSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ForSyrup {
            get {
                return ResourceManager.GetString("txt_ForSyrup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string txt_FromDate {
            get {
                return ResourceManager.GetString("txt_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_HiveListMainPageTitle {
            get {
                return ResourceManager.GetString("txt_HiveListMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Uli.
        /// </summary>
        internal static string txt_HiveListTitle {
            get {
                return ResourceManager.GetString("txt_HiveListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review History.
        /// </summary>
        internal static string txt_HiveReviewHistory {
            get {
                return ResourceManager.GetString("txt_HiveReviewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Review.
        /// </summary>
        internal static string txt_InvalidReview {
            get {
                return ResourceManager.GetString("txt_InvalidReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        internal static string txt_InvalidValue {
            get {
                return ResourceManager.GetString("txt_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string txt_ItemName {
            get {
                return ResourceManager.GetString("txt_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ItemQuantity {
            get {
                return ResourceManager.GetString("txt_ItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Unit.
        /// </summary>
        internal static string txt_ItemUnit {
            get {
                return ResourceManager.GetString("txt_ItemUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_LanguageSettingsMainPageTitle {
            get {
                return ResourceManager.GetString("txt_LanguageSettingsMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_MainPageTitle {
            get {
                return ResourceManager.GetString("txt_MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt_MassUnit.
        /// </summary>
        internal static string txt_MassUnit {
            get {
                return ResourceManager.GetString("txt_MassUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string txt_Modify {
            get {
                return ResourceManager.GetString("txt_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Name {
            get {
                return ResourceManager.GetString("txt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_NewQueen {
            get {
                return ResourceManager.GetString("txt_NewQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_NewRace {
            get {
                return ResourceManager.GetString("txt_NewRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_No {
            get {
                return ResourceManager.GetString("txt_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Date.
        /// </summary>
        internal static string txt_NoDate {
            get {
                return ResourceManager.GetString("txt_NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Queen.
        /// </summary>
        internal static string txt_NoQueen {
            get {
                return ResourceManager.GetString("txt_NoQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string txt_OK {
            get {
                return ResourceManager.GetString("txt_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_OneToOne {
            get {
                return ResourceManager.GetString("txt_OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_PhotoList {
            get {
                return ResourceManager.GetString("txt_PhotoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned:.
        /// </summary>
        internal static string txt_Planned {
            get {
                return ResourceManager.GetString("txt_Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_PlannedDate {
            get {
                return ResourceManager.GetString("txt_PlannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Number.
        /// </summary>
        internal static string txt_PleaseEnterValidNumber {
            get {
                return ResourceManager.GetString("txt_PleaseEnterValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ProductionTypeNamePlaceholder {
            get {
                return ResourceManager.GetString("txt_ProductionTypeNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_QueenListMainPageTitle {
            get {
                return ResourceManager.GetString("txt_QueenListMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string txt_Race {
            get {
                return ResourceManager.GetString("txt_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_RaceNamePlaceholder {
            get {
                return ResourceManager.GetString("txt_RaceNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized:.
        /// </summary>
        internal static string txt_Realized {
            get {
                return ResourceManager.GetString("txt_Realized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Hive.
        /// </summary>
        internal static string txt_RemoveHive {
            get {
                return ResourceManager.GetString("txt_RemoveHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Queen.
        /// </summary>
        internal static string txt_RemoveQueen {
            get {
                return ResourceManager.GetString("txt_RemoveQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_RequestValue {
            get {
                return ResourceManager.GetString("txt_RequestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Result {
            get {
                return ResourceManager.GetString("txt_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ReviewDetailsMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ReviewDetailsMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ReviewHistoryMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ReviewHistoryMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ReviewListMainPageTitle {
            get {
                return ResourceManager.GetString("txt_ReviewListMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ReviewNamePlaceholder {
            get {
                return ResourceManager.GetString("txt_ReviewNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ReviewNotificationDescription {
            get {
                return ResourceManager.GetString("txt_ReviewNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ReviewNotificationTitle {
            get {
                return ResourceManager.GetString("txt_ReviewNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Type.
        /// </summary>
        internal static string txt_ReviewType {
            get {
                return ResourceManager.GetString("txt_ReviewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string txt_Save {
            get {
                return ResourceManager.GetString("txt_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string txt_Search {
            get {
                return ResourceManager.GetString("txt_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukana Fraza.
        /// </summary>
        internal static string txt_SearchPhrase {
            get {
                return ResourceManager.GetString("txt_SearchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_SelectCalculationTargetType {
            get {
                return ResourceManager.GetString("txt_SelectCalculationTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_SelectProduct {
            get {
                return ResourceManager.GetString("txt_SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_SelectQueen {
            get {
                return ResourceManager.GetString("txt_SelectQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_SelectRatio {
            get {
                return ResourceManager.GetString("txt_SelectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_SelectUnit {
            get {
                return ResourceManager.GetString("txt_SelectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_SettingsNavigationTitle {
            get {
                return ResourceManager.GetString("txt_SettingsNavigationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soon.
        /// </summary>
        internal static string txt_Soon {
            get {
                return ResourceManager.GetString("txt_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Sugar {
            get {
                return ResourceManager.GetString("txt_Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_SugarToWaterRatio {
            get {
                return ResourceManager.GetString("txt_SugarToWaterRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Syrup {
            get {
                return ResourceManager.GetString("txt_Syrup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_TakePhoto {
            get {
                return ResourceManager.GetString("txt_TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test_default.
        /// </summary>
        internal static string txt_Test {
            get {
                return ResourceManager.GetString("txt_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ThreeToTwo {
            get {
                return ResourceManager.GetString("txt_ThreeToTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string txt_ToDate {
            get {
                return ResourceManager.GetString("txt_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_TwoToOne {
            get {
                return ResourceManager.GetString("txt_TwoToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_TypeValue {
            get {
                return ResourceManager.GetString("txt_TypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompleted All Review.
        /// </summary>
        internal static string txt_UncompletedAllReview {
            get {
                return ResourceManager.GetString("txt_UncompletedAllReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncopleted.
        /// </summary>
        internal static string txt_Uncopleted {
            get {
                return ResourceManager.GetString("txt_Uncopleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ValueEdit {
            get {
                return ResourceManager.GetString("txt_ValueEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_ValuePlaceholder {
            get {
                return ResourceManager.GetString("txt_ValuePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt_VolumeUnit.
        /// </summary>
        internal static string txt_VolumeUnit {
            get {
                return ResourceManager.GetString("txt_VolumeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_WarehouseMainPageTitle {
            get {
                return ResourceManager.GetString("txt_WarehouseMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Water {
            get {
                return ResourceManager.GetString("txt_Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string txt_Yes {
            get {
                return ResourceManager.GetString("txt_Yes", resourceCulture);
            }
        }
    }
}
